### PR TITLE
Multiple fixes (code logic and issues)

### LINKED ISSUE #5: Color issues when repacking
Repacking a folder containing unedited extracted PNG files causes color issues in the repacked XET file:
Original image:
original

Repacked image:
repacked

### PR DESCRIPTION
**Pull request by AntonioDePau**

### CODE REVIEW

File: ConsoleProject/src/services/TextureConverter.cs [hunk 1]
```diff
@@ -182,10 +182,10 @@ public class TextureConverter {
             file.InsertRange(4, BitConverter.GetBytes(1).ToList());
 
             file.RemoveRange(8, 2);
-            file.InsertRange(8, BitConverter.GetBytes(header.FileCount).ToList());
+            file.InsertRange(8, BitConverter.GetBytes((short)header.FileCount).ToList());
 
             file.RemoveRange(10, 2);
-            file.InsertRange(10, BitConverter.GetBytes(header.FileCountB).ToList());
+            file.InsertRange(10, BitConverter.GetBytes((short)header.FileCountB).ToList());
```
Comment (AntonioDePau) [inline ConsoleProject/src/services/TextureConverter.cs]: FileCount and FileCountB must be written as short, otherwise the whole file will be 4 bytes longer than expected.

**Comment by Andrew9x** [comment]
Give the pull request a title please.

File: ConsoleProject/src/services/TextureConverter.cs [hunk 2]
```diff
@@ -75,8 +75,39 @@ public class TextureConverter {
...
             return texture;
         }
-
+        
         private Bitmap GetBitmapFromPalette(Texture texture) {
+            Bitmap bmp = new Bitmap(texture.Width, texture.Height);
+            int row = 0;
+            int bitsPerPixelMultiplier = 8 / texture.BitsPerPixel;
+
+            List<System.Drawing.Color> colors = new List<System.Drawing.Color>();
```
Comment (Andrew9x) [inline ConsoleProject/src/services/TextureConverter.cs]: Move this to the imports. Only use Color class here.

File: ConsoleProject/src/services/TextureConverter.cs [hunk 3]
```diff
@@ -75,8 +75,39 @@ public class TextureConverter {
...
+            
+            for (int c = 0; c < texture.Palette.Length / 4; c++) {
```
Comment (Andrew9x) [inline ConsoleProject/src/services/TextureConverter.cs]: Move this to a private method, with return type: List<Colors>.
As parameter pass the texture.Palette array.

On this level call this only:
texture.colors.AddAll( privateMethod );

File: ConsoleProject/src/services/TextureConverter.cs [hunk 4]
```diff
@@ -75,8 +75,39 @@ public class TextureConverter {
...
+                Color col = Color.FromArgb(texture.Palette[c * 4 + 3], texture.Palette[c * 4], texture.Palette[c * 4 + 1], texture.Palette[c * 4 + 2]);
+                texture.Colors.Add(col);
+            }
+
+            for (int x = 0; x < texture.Unswizzled.Length; x++) {
```
Comment (Andrew9x) [inline ConsoleProject/src/services/TextureConverter.cs]: Move this to a private method., with return type of Bitmap.
Pass the color array, the unswizzled array and the with as parameter.

File: ConsoleProject/src/services/TextureConverter.cs [hunk 5]
```diff
@@ -75,8 +75,39 @@ public class TextureConverter {
...
+                if (x >= texture.Width + (texture.Width * row)) row++;
```
Comment (Andrew9x) [inline ConsoleProject/src/services/TextureConverter.cs]: Alawys use brackets.

File: ConsoleProject/src/services/TextureConverter.cs [hunk 6]
```diff
@@ -182,10 +214,10 @@ public class TextureConverter {
             file.InsertRange(4, BitConverter.GetBytes(1).ToList());
 
             file.RemoveRange(8, 2);
-            file.InsertRange(8, BitConverter.GetBytes(header.FileCount).ToList());
+            file.InsertRange(8, BitConverter.GetBytes((short)header.FileCount).ToList());
```
Comment (Andrew9x) [inline ConsoleProject/src/services/TextureConverter.cs]: Instead of casting change these fields in TexHeaderMap from integer to short datatype.

File: ConsoleProject/src/services/TextureConverter.cs (hunk 1 above)
Comment (Andrew9x) [reply ConsoleProject/src/services/TextureConverter.cs]: See my comment above.

File: ConsoleProject/src/view/Frontend.cs [hunk 7]
```diff
@@ -12,17 +12,20 @@ namespace ConsoleProject.View {
 
     public class Frontend {
 
+        private string AppName = "XetTex Viewer";
```
Comment (Andrew9x) [inline ConsoleProject/src/view/Frontend.cs]: This can be static. Static variable names should be uppercase.

File: ConsoleProject/src/view/Frontend.cs [hunk 8]
```diff
@@ -108,7 +104,12 @@ public class Frontend {
                 Anchor = (AnchorStyles.Left | AnchorStyles.Bottom | AnchorStyles.Right)
             };
 
-            infoPanel.Controls.Add(labelInfo);
+            infoPanel.Controls.Add(labelImageInfo);
+            //Not sure if the following 3 lines should be here or somewhere else?
```
Comment (Andrew9x) [inline ConsoleProject/src/view/Frontend.cs:117]: They are fine here currently. Will be moved to a private method later.

File: ConsoleProject/src/view/Frontend.cs [hunk 9]
```diff
@@ -156,18 +178,20 @@ public class Frontend {
                 imageListBox.SelectedIndex = 0;
             }
             DisplayImage();
+            form.Text = AppName + " - " + Path.GetFileName(filename);
```
Comment (Andrew9x) [inline ConsoleProject/src/view/Frontend.cs:180]: I don't see why is this info required.

File: ConsoleProject/src/view/Frontend.cs [hunk 10]
```diff
@@ -185,22 +209,55 @@ public class Frontend {
...
+                                                
+                        string logContent = "";
+                        
                         for (int y = 0; y < bmp2.Height; y++) {
                             for (int x = 0; x < bmp2.Height; x++) {
                                 Color c = bmp2.GetPixel(x, y);
                                 if (palette.IndexOf(c) == -1) {
                                     if (palette.Count < 256) palette.Add(c);
                                 }
+                                if (completeColors.IndexOf(c) == -1) completeColors.Add(c);
```
Comment (Andrew9x) [inline ConsoleProject/src/view/Frontend.cs]: Add missing brackets.

File: ConsoleProject/src/view/Frontend.cs [hunk 11]
```diff
@@ -185,22 +209,55 @@ public class Frontend {
...
+                        }
+                        logContent += "\n\n";
+                        
                         while (palette.Count < 16) palette.Insert(0, Color.FromArgb(0, 0, 0, 0));
 
                         if (palette.Count > 16) while (palette.Count < 256) palette.Insert(0, Color.FromArgb(0, 0, 0, 0));
 
                         palette.Sort((x, y) => x.A.CompareTo(y.A));
+                        
+                        if (log) {
```
Comment (Andrew9x) [inline ConsoleProject/src/view/Frontend.cs:255]: We'll use a logging framework for this. Please add a TODO comment here: "replace with Logger"

File: ConsoleProject/src/view/Frontend.cs [hunk 12]
```diff
@@ -241,6 +302,7 @@ public class Frontend {
                                 dataIndex++;
                             }
                         }
+                        if (log) File.WriteAllText(file + ".log.txt", logContent);
```
Comment (Andrew9x) [inline ConsoleProject/src/view/Frontend.cs]: Add missing brackets.

File: ConsoleProject/src/view/Frontend.cs [hunk 13]
```diff
@@ -125,13 +126,34 @@ public class Frontend {
...
+                    this.LoadImages(fileList[0]);
+                } catch (InvalidDataException ex) {
+                    Console.WriteLine(ex);
+                    MessageBox.Show("No images found!\nIncorrect file?");
+                }
+            }
+        }
 
         private void DrawPicture(MouseEventArgs mouseEvent = null) {
+            if (obmp == null) return;
```
Comment (Andrew9x) [inline ConsoleProject/src/view/Frontend.cs]: Add missing brackets. Also write an info log to the console, why is this an error. If it's an error maybe throwing an exception is better. I haven't yet understood the connection between bmp and obmp.

File: ConsoleProject/src/view/Frontend.cs [hunk 14]
```diff
@@ -125,13 +126,34 @@ public class Frontend {
             };
             return listBox;
         }
+        
+        private void ParseNewFile(string[] fileList) {
```
Comment (Andrew9x) [inline ConsoleProject/src/view/Frontend.cs]: This method should not be in the FrontEnd layer. A better place would be in the TextureConverter class.

File: ConsoleProject/src/view/Frontend.cs [hunk 15]
```diff
@@ -125,13 +126,34 @@ public class Frontend {
...
+            if (fileList.Length > 0) { // is this IF required?
```
Comment (Andrew9x) [inline ConsoleProject/src/view/Frontend.cs]: I'm surprised that this doesn't throw a null pointer exception.

File: ConsoleProject/Application.cs [hunk 16]
```diff
@@ -6,8 +6,8 @@ namespace ConsoleProject {
     class Application {
 
         [STAThread]
-        public static void Main() {
-            new Frontend().ShowForm();
+        public static void Main(string[] arguments) {
+            new Frontend().ShowForm(arguments);
```
Comment (Andrew9x) [inline ConsoleProject/Application.cs]: I don't like that we are passing "arguments" to the frontend.
Renaming them to "filelist" would be better in the ShowForm method signature.

However the ultimate goal is to seperate the console and the frontend layers. Thus the frontEnd should not require the console inputs. The underlying layers (eg texture converter) should be able to service both the windows form frontend and the console frontend.

**Review by Andrew9x — CHANGES_REQUESTED** [review]

File: ConsoleProject/src/view/Frontend.cs (hunk 9 above)
Comment (AntonioDePau) [reply ConsoleProject/src/view/Frontend.cs:180]: Just for conveniency of knowing which file is currently being loaded.
Helped me a couple of times when trying multiple repackings with the same images and a repack wouldn't correctly load (without displaying any errors). But I understand where this is coming from, and there should be an error message displayed at some point rather than doing this.

However, most apps that open files do display the filename in the title bar (notepad, paint, etc.)

File: ConsoleProject/src/view/Frontend.cs (hunk 13 above)
Comment (AntonioDePau) [reply ConsoleProject/src/view/Frontend.cs]: I think this happens when no XET (and thus bitmap) has been loaded.
Example: You start the EXE without providing a file, so the form shows, but no default image is loaded.
If at this point you do not return from this function, you get an exception when trying to zoom in or out.

As for bmp vs obmp, bmp is the currently displayed image (including zoom level) while obmp is the original image (default zoom) which allows for the ratio calculation.

File: ConsoleProject/Application.cs (hunk 16 above)
Comment (AntonioDePau) [reply ConsoleProject/Application.cs]: If this is only a naming issue, fine, it can be renamed.
However, I would prefer to keep the possibility to pass files as arguments, not necessarily via console input, but rather as a drag-and-drop on the exe or double-click with the exe set as the default opening program.

File: ConsoleProject/src/services/TextureConverter.cs (hunk 6 above)
Comment (AntonioDePau) [reply ConsoleProject/src/services/TextureConverter.cs]: Thought you changed them and that's what they were originally :D alright, will change.

File: ConsoleProject/src/services/TextureConverter.cs (hunk 4 above)
Comment (AntonioDePau) [reply ConsoleProject/src/services/TextureConverter.cs]: Isn't this what the method GetBitmapFromPalette is already doing?
Also, not sure I committed this already, but there are now 2 methods: GetIndexedBitmapFromPalette and GetBitmapFromPalette. Each need a different way of iterating through Unswizzled. So, I would rather keep those two methods as they are.

File: ConsoleProject/src/view/Frontend.cs (hunk 15 above)
Comment (AntonioDePau) [reply ConsoleProject/src/view/Frontend.cs]: Not sure what this means or what I should do about it.
This is just to check if there's any file at all being passed to this method.
I could also return if the length is Zero if you prefer.

File: ConsoleProject/src/view/Frontend.cs (hunk 14 above)
Comment (AntonioDePau) [reply ConsoleProject/src/view/Frontend.cs]: Moving it to TextureConverter makes it more difficult to interact with Frontend and populate the "images" list only if the file is valid though. I'll see what I can do...

File: ConsoleProject/src/services/TextureConverter.cs (hunk 6 above)
Comment (Andrew9x) [reply ConsoleProject/src/services/TextureConverter.cs]: Yes it does ring a bell. I didn't understand the purpose back then.

File: ConsoleProject/src/view/Frontend.cs (hunk 15 above)
Comment (Andrew9x) [reply ConsoleProject/src/view/Frontend.cs]: Check ShowForm signature: arguments is an optional parameter. If it is not provided then it'll get initialized as null.

Here you are calling a property on a null object. Which should throw an exception.

File: ConsoleProject/Application.cs (hunk 16 above)
Comment (Andrew9x) [reply ConsoleProject/Application.cs]: "double-click with the exe set as the default opening program." 
Haven't thought about this, good point. 

At the Application layer we can work with it as arguments, thats fine.
But the form should already know what is it getting as parameter, thus the need of rename.

Some sort of validation might be a good idea too. Perhaps add a todo here, to validate the input arguments.

File: ConsoleProject/src/view/Frontend.cs (hunk 14 above)
Comment (AntonioDePau) [reply ConsoleProject/src/view/Frontend.cs]: So... I moved it here (TextureConverter.cs):
image

However, since I cannot interact with the Frontend, the conditions have to be based on the return value of the method, so it means that I have double (triple?) the code in Frontend to achieve the same result as before:
image

File: ConsoleProject/src/services/TextureConverter.cs [hunk 17]
```diff
@@ -75,20 +88,61 @@ public class TextureConverter {
 
             return texture;
         }
-
+        
+        private List<Color> GetColorsFromPalette(byte[] palette) {
+            List<Color> colors = new List<Color>();
+            for (int c = 0; c < palette.Length / 4; c++) {
```
Comment (Andrew9x) [inline ConsoleProject/src/services/TextureConverter.cs]: Don't divide the length by 4.
Increment by using `c+=4` instead of `c++`;
Also use`i` as index variable instead of `c`.

Benefits: we don't need the multiplication of `c * 4`.

File: ConsoleProject/src/view/Frontend.cs [hunk 18]
```diff
@@ -146,7 +170,7 @@ public class Frontend {
             pictureBox.Size = bmp.Size;
         }
 
-        private void LoadImages() {
+        public void LoadImages(string filename) {
```
Comment (Andrew9x) [inline ConsoleProject/src/view/Frontend.cs]: Why did this method had to become public?

**Review by Andrew9x — CHANGES_REQUESTED** [review]

File: ConsoleProject/src/view/Frontend.cs (hunk 18 above)
Comment (AntonioDePau) [reply ConsoleProject/src/view/Frontend.cs]: Mhhh... Forgot to revert it back to Private.
That was when I thought I could interact with it from TextureConverter. Fixed.

File: ConsoleProject/src/services/TextureConverter.cs (hunk 17 above)
Comment (AntonioDePau) [reply ConsoleProject/src/services/TextureConverter.cs]: Done!

File: ConsoleProject/src/services/TextureConverter.cs [hunk 19]
```diff
@@ -30,6 +30,19 @@ public class TextureConverter {
...
         }
 
+        public List<Texture> ParseNewFile(string[] fileList) {
+            if (fileList != null) { // is this IF required?
+                try {
+                     // TODO only reads first file
+                    return ParseFile(fileList[0]);
+                } catch (InvalidDataException ex) {
+                    Console.WriteLine(ex);
+                    return null;
```
Comment (Andrew9x) [inline ConsoleProject/src/services/TextureConverter.cs]: Avoid returning with null. Returning with null always causes a null check in the caller layer. Usually only the not-null case is handled, without the else branch. 

I changed the original null return to exception throwing. An exception must be handled, unlike a null return.

Comment (Andrew9x) [reply ConsoleProject/src/services/TextureConverter.cs]: Here I would remove the try catch, and move it to the caller layer. Let the exception propagate upward.

File: ConsoleProject/src/services/TextureConverter.cs [hunk 20]
```diff
@@ -99,7 +153,9 @@ public class TextureConverter {
             System.Runtime.InteropServices.Marshal.Copy(data.Scan0, bytes, 0, bytes.Length);
 
             for (int x = 0; x < texture.Unswizzled.Length; x++) {
-                if (x >= texture.Width + (texture.Width * row)) row++;
+                if (x >= texture.Width + (texture.Width * row)){
```
Comment (Andrew9x) [inline ConsoleProject/src/services/TextureConverter.cs:143]: Could you explain this condition? It feels like it can be replaced with modulo arithmetic.
if ( x % texture.Width == 0) { row++; }

File: ConsoleProject/src/view/Frontend.cs [hunk 21]
```diff
@@ -46,18 +49,23 @@ public class Frontend {
...
-                    try {
-                        images = new TextureConverter().ParseFile(fileList[0]); // TODO only reads first file
-                        this.LoadImages();
-                    } catch (InvalidDataException ex) {
-                        Console.WriteLine(ex);
-                        MessageBox.Show("No images found!\nIncorrect file?");
-                    }
+                string[] filesDropped = (string[])e.Data.GetData(DataFormats.FileDrop, false);
+                List<Texture> listDropped = new TextureConverter().ParseNewFile(filesDropped);
+                if (listDropped != null) {
```
Comment (Andrew9x) [inline ConsoleProject/src/view/Frontend.cs]: Replace null check with exception handling. Also extract the common part to a private function here. This will solve your code duplication concerns too.

**Review by Andrew9x — CHANGES_REQUESTED** [review]

File: ConsoleProject/src/services/TextureConverter.cs (hunk 20 above)
Comment (AntonioDePau) [reply ConsoleProject/src/services/TextureConverter.cs:143]: Indeed, changed to modulo!

**Review by Andrew9x — APPROVED** [review]
